import type { ConfigState } from '../../types/config';
import { getBoardProfile } from './boardProfiles';
import { generateStyleString } from './styleTemplates';

function bladeTypeToProffie(bladeType: string, ledCount: number, board: ReturnType<typeof getBoardProfile>): string {
  const { bladePin, powerPins } = board;
  const powerStr = powerPins.map(p => `bladePowerPin${p.replace(/\D/g, '')}`).join(', ');

  switch (bladeType) {
    case 'APA102':
      return `APA102BladePtr<${ledCount}, ${bladePin}, PowerPINS<${powerStr}>>()`;
    case 'SIMPLE_LED':
      return `SimpleBladePtr<CreeXPE2RedTemplate<0>, CreeXPE2GreenTemplate<0>, CreeXPE2BlueTemplate<0>, NoLED, bladePowerPin1, bladePowerPin2, bladePowerPin3, -1>()`;
    default:
      return `WS2811BladePtr<${ledCount}, ${bladePin}, Color8::WHITE, PowerPINS<${powerStr}>>()`;
  }
}

function indent(str: string, spaces: number): string {
  const pad = ' '.repeat(spaces);
  return str.split('\n').map(l => pad + l).join('\n');
}

function boardInclude(board: string): string {
  switch (board) {
    case 'v1':    return 'proffieboard_v1_config.h';
    case 'v2.2':  return 'proffieboard_v2_config.h';
    case 'lite':  return 'proffieboard_lite_config.h';
    default:      return 'proffieboard_v3_config.h';
  }
}

function buttonConfig(numButtons: number): string {
  const lines = ['Button PowerButton(BUTTON_POWER, powerButtonPin, "pow");'];
  if (numButtons >= 2) lines.push('Button AuxButton(BUTTON_AUX, auxPin, "aux");');
  if (numButtons >= 3) lines.push('Button Aux2Button(BUTTON_AUX2, aux2Pin, "aux2");');
  return lines.join('\n');
}

export function generateConfig(state: ConfigState): string {
  const { hardware, fonts } = state;
  const board = getBoardProfile(hardware.board);
  const features = hardware.features;
  const numBlades = hardware.blades.length;

  // Build preset blocks — one entry per font preset
  const presetBlocks = fonts.map(font => {
    const folder = font.folderName || 'font';
    const track = font.trackFile || `${folder}/tracks/track.wav`;

    // One style per blade; pad with first style if font has fewer styles than blades
    const styleLines = hardware.blades.map((_blade, i) => {
      const styleCfg = font.bladeStyles?.[i] ?? font.bladeStyles?.[0];
      return styleCfg ? indent(generateStyleString(styleCfg), 4) : '    StylePtr<Solid<Rgb<0,0,255>>>()';
    });

    return `  { "${folder}", "${track}",\n${styleLines.join(',\n')},\n    "name=${font.name}"\n  }`;
  });

  // Blade hardware config
  const bladeConfigs = hardware.blades.map(blade => {
    const ptr = bladeTypeToProffie(blade.bladeType, blade.ledCount, board);
    return `  SubBladePtr<0, ${blade.ledCount - 1}, ${ptr}>`;
  });

  // Feature defines
  const defines: string[] = [];
  if (features.enableAudio)  defines.push('#define ENABLE_AUDIO');
  if (features.enableMotion) defines.push('#define ENABLE_MOTION');
  if (features.enableSD)     defines.push('#define ENABLE_SD');
  if (features.enableOLED)   defines.push('#define ENABLE_DISPLAY\n#include "display/ssd1306.h"');
  if (features.enableBluetooth) defines.push('#define ENABLE_BLUETOOTH');
  if (features.enableSerial) defines.push('#define ENABLE_SERIAL');
  if (features.batteryLevelOnStart) defines.push('#define BATTERY_LEVEL_ON_START');

  const hasWS = hardware.blades.some(b => b.bladeType === 'WS2811' || b.bladeType === 'WS2812B' || b.bladeType === 'NEOPIXEL');
  const hasAPA = hardware.blades.some(b => b.bladeType === 'APA102');
  if (hasWS)  defines.push('#define ENABLE_WS2811');
  if (hasAPA) defines.push('#define ENABLE_SPI_LEDS');

  const volumeLine = `float volume = ${(features.volume / 100).toFixed(2)}f;`;

  return `// Proffie Config generated by ProffieAI
// Board: ${board.label}  |  Buttons: ${features.numButtons}  |  Fonts: ${fonts.length}
// Generated: ${new Date().toISOString()}

#ifdef CONFIG_TOP
#include "${boardInclude(hardware.board)}"
const int kNumBlades = ${numBlades};
const int kNumButtons = ${features.numButtons};
${volumeLine}
${defines.join('\n')}
#endif

#ifdef CONFIG_PROP
#include "../props/saber_sa22c_buttons.h"
#endif

#ifdef CONFIG_PRESETS
Preset presets[] = {
${presetBlocks.join(',\n')}
};

BladeConfig blades[] = {
 { 0,
${bladeConfigs.join(',\n')},
   CONFIGARRAY(presets)
 }
};
#endif

#ifdef CONFIG_BUTTONS
${buttonConfig(features.numButtons)}
#endif
`;
}
